### PR TITLE
Pull request approval for main project route structure and template set up

### PR DESCRIPTION
**Pull request by HuangStanley050**
Pleaes review pull request and go over with Chris and rest of the team to see if the template and route set up is suitable. Thank you

### CODE REVIEW

**Review by Apochilles — CHANGES_REQUESTED** [review]
The authors need to be updated to all collaborators. Is this the package file for the app? I have no experience building a full a MERN stack app so if you could fill me in a little on what you are planning that would be great Stanley.

**Review by Apochilles — CHANGES_REQUESTED** [review]
Not entirely sure how a API router works but we also need Sets represented. I think we should all have a discussion about what we're working on.

**Comment by HuangStanley050** [comment]
The minimum npm package for MERN REST api is the express module, we might need to add additional packages as we go. I am unsure how to update all contributors from this pull request.

**Comment by Apochilles** [comment]
Keep it updated to Chris, me and you for now

**Pull request closed without merging**
